In [3]:
import pandas as pd
import numpy as np
print("Libraries installed successfully")

Libraries installed successfully

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\Saranya Jenita\Downloads\Dataset .csv", encoding='latin1')

print("First 5 rows of dataset:")
display(df.head())

print("Shape of dataset (rows, columns):", df.shape)

print("\nColumn names:")

print("\nDataset info:")
df.info()

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nStatistical summary:")
display(df.describe())

print("\nNumber of duplicate rows:", df.duplicated().sum())

First 5 rows of dataset:

,ï»¿Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

Shape of dataset (rows, columns): (9551, 21)

Column names:

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ï»¿Restaurant ID      9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Switch to order menu  9551 non-null   str
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   str
 19  Rating text           9551 non-null   str
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), str(13)
memory usage: 1.5 MB

Missing values in each column:
ï»¿Restaurant ID        0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

Statistical summary:

,ï»¿Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

Number of duplicate rows: 0

In [3]:
df.columns = df.columns.str.replace('ï»¿', '', regex=False)

selected_columns = [
    'Country Code',
    'City',
    'Longitude',
    'Latitude',
    'Cuisines',
    'Average Cost for two',
    'Has Table booking',
    'Has Online delivery',
    'Price range',
    'Votes',
    'Aggregate rating'
]

df_task1 = df[selected_columns].copy()

print("Selected columns dataset:")
display(df_task1.head())

print("\nMissing values before handling:")
print(df_task1.isnull().sum())

df_task1 = df_task1.dropna(subset=['Aggregate rating'])

df_task1['Cuisines'] = df_task1['Cuisines'].fillna(df_task1['Cuisines'].mode()[0])
df_task1['City'] = df_task1['City'].fillna(df_task1['City'].mode()[0])

df_task1['Average Cost for two'] = df_task1['Average Cost for two'].fillna(df_task1['Average Cost for two'].median())
df_task1['Votes'] = df_task1['Votes'].fillna(df_task1['Votes'].median())
df_task1['Longitude'] = df_task1['Longitude'].fillna(df_task1['Longitude'].median())
df_task1['Latitude'] = df_task1['Latitude'].fillna(df_task1['Latitude'].median())

print("\nMissing values after handling:")
print(df_task1.isnull().sum())

print("\nShape after cleaning:", df_task1.shape)

print("\nCleaned dataset info:")
df_task1.info()

Selected columns dataset:

,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Votes,Aggregate rating
0,162,Makati City,121.027535,14.565443,"French, Japanese, Desserts",1100,Yes,No,3,314,4.8
1,162,Makati City,121.014101,14.553708,Japanese,1200,Yes,No,3,591,4.5
2,162,Mandaluyong City,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Yes,No,4,270,4.4
3,162,Mandaluyong City,121.056475,14.585318,"Japanese, Sushi",1500,No,No,4,365,4.9
4,162,Mandaluyong City,121.057508,14.584450,"Japanese, Korean",1500,Yes,No,4,229,4.8

Missing values before handling:
Country Code            0
City                    0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Has Table booking       0
Has Online delivery     0
Price range             0
Votes                   0
Aggregate rating        0
dtype: int64

Missing values after handling:
Country Code            0
City                    0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Has Table booking       0
Has Online delivery     0
Price range             0
Votes                   0
Aggregate rating        0
dtype: int64

Shape after cleaning: (9551, 11)

Cleaned dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country Code          9551 non-null   int64
 1   City                  9551 non-null   str
 2   Longitude             9551 non-null   float64
 3   Latitude              9551 non-null   float64
 4   Cuisines              9551 non-null   str
 5   Average Cost for two  9551 non-null   int64
 6   Has Table booking     9551 non-null   str
 7   Has Online delivery   9551 non-null   str
 8   Price range           9551 non-null   int64
 9   Votes                 9551 non-null   int64
 10  Aggregate rating      9551 non-null   float64
dtypes: float64(3), int64(4), str(4)
memory usage: 820.9 KB

In [4]:
df_model = df_task1.copy()

df_model['Has Table booking'] = df_model['Has Table booking'].map({'Yes': 1, 'No': 0})

df_model['Has Online delivery'] = df_model['Has Online delivery'].map({'Yes': 1, 'No': 0})

df_model[['Has Table booking', 'Has Online delivery']].head()

   Has Table booking  Has Online delivery
0                  1                    0
1                  1                    0
2                  1                    0
3                  0                    0
4                  1                    0

In [5]:
y = df_model['Aggregate rating']

X = df_model.drop('Aggregate rating', axis=1)

X = pd.get_dummies(
    X,
    columns=['City', 'Cuisines'],
    drop_first=True
)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

X.head()

Shape of X: (9551, 1972)
Shape of y: (9551,)

,Country Code,Longitude,Latitude,Average Cost for two,Has Table booking,Has Online delivery,Price range,Votes,City_Agra,City_Ahmedabad,...,"Cuisines_Turkish, Arabian, Middle Eastern","Cuisines_Turkish, Arabian, Moroccan, Lebanese","Cuisines_Turkish, Mediterranean, Middle Eastern",Cuisines_Vietnamese,"Cuisines_Vietnamese, Fish and Chips","Cuisines_Western, Asian, Cafe","Cuisines_Western, Fusion, Fast Food",Cuisines_World Cuisine,"Cuisines_World Cuisine, Mexican, Italian","Cuisines_World Cuisine, Patisserie, Cafe"
0,162,121.027535,14.565443,1100,1,0,3,314,False,False,...,False,False,False,False,False,False,False,False,False,False
1,162,121.014101,14.553708,1200,1,0,3,591,False,False,...,False,False,False,False,False,False,False,False,False,False
2,162,121.056831,14.581404,4000,1,0,4,270,False,False,...,False,False,False,False,False,False,False,False,False,False
3,162,121.056475,14.585318,1500,0,0,4,365,False,False,...,False,False,False,False,False,False,False,False,False,False
4,162,121.057508,14.584450,1500,1,0,4,229,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (7640, 1972)
Testing Features  : (1911, 1972)
Training Target   : (7640,)
Testing Target    : (1911,)

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [8]:
y_pred = model.predict(X_test)

print("First 10 Predictions:")
print(y_pred[:10])

First 10 Predictions:
[1.51516387 3.32166205 2.02566771 2.75344199 2.05013564 2.54114282
 2.9540427  2.08153635 2.32188628 3.40989483]

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Model Evaluation")
print("------------------------")
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R2 Score:", r2)

Model Evaluation
------------------------
Mean Absolute Error (MAE): 0.9616373739655254
Mean Squared Error (MSE): 1.4112720147489652
Root Mean Squared Error (RMSE): 1.1879697027908436
R2 Score: 0.37996290126815335

In [ ]:
CONCLUSION

A Linear Regression model was built to predict restaurant aggregate ratings.

The dataset was cleaned, missing values were handled, categorical features were encoded, and the data was split into training and testing sets.

The model was evaluated using MAE, MSE, RMSE, and R² Score.

Results:
- MAE: 0.9616
- MSE: 1.4113
- RMSE: 1.1880
- R² Score: 0.3800

The model is able to predict restaurant ratings with moderate accuracy and demonstrates the complete machine learning workflow from preprocessing to evaluation.